### ISSUE TITLE
Installing without composer

### ISSUE THREAD

**Issue by oldcastlehq** [Pixelrobin/php-feather#1]
How can I install it without using composer? I have some restrictions in my current project, so I cannot use composer. Could you add manual instructions?

**Comment by Pixelrobin** [comment]
Using this without composer should be fairly simple, and I'll add instructions for that in the future, thanks!
For now, you can just download the repository as a zip...

![image](https://user-images.githubusercontent.com/17094139/49043629-7c667f00-f180-11e8-8d0a-72e06201c518.png)

And then extract the files wherever you wish in your project. You can delete The `composer.json` and `composer.lock` files if you're not using composer. Then, just require the file as normal in your project.

```php
<?php

require __DIR__ . '.path/to/feather/src/Icons.php';

$icons = new Feather\Icons;
$icons->get('anchor');
```

Sorry for the late reply!

**Comment by oldcastlehq** [comment]
Solved! Thanks!
