### ISSUE TITLE
[RFC] PHP Support

### ISSUE THREAD

**Issue by natewiebe13** [Pixelrobin/php-feather#14]
This one might be a bit contentious, but I believe that we should change PHP support to be restricted to `>=7.3` with 7.3 being the oldest supported version: https://www.php.net/supported-versions.php

This will allow us to help provide a reason to keep PHP up to date as well as allow us to take advantage of newer PHP versions.

**Comment by michaelsavchuk** [comment]
I agree. No sense in carrying the burden of supporting a deprecated version of PHP, especially in version 2.0.
I think once #16 is resolved and merged this can be done to avoid further conflicts.
