### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by natewiebe13** [Pixelrobin/php-feather#18]
Add the ability to add custom icons. This allows being able to start off a project with Feather Icons and then if some need tweaks or new icons based on branding, this lib can be used instead of adding on another solution.

**Comment by michaelsavchuk** [comment]
I can see how this can be helpful but I'm not immediately on board with it. It just feels a little out of scope for the library. I'm open to change my mind though.

I feel like if this was really needed down the line, with my proposal in #19 as a user you could just extend the `Icons` class and write this logic into it. For example:

```php
<?php
class MyIcons extends Icons
{
    private $customIcons;

    public function __construct()
    {
        $this->customIcons = getSomeCustomIcons();
        parent::__construct();
    }

    public function get($name, $attributes)
    {
        if (array_key_exists($name, $this->customIcons)) {
            return $this->customIcons[$name];
        } else {
            return parent::get($name, $attributes);
        }
    }
}
```

But still writing that out I can see the benefit of just having a simple `addIcon()` helper...

I'm not as involved in PHP as I used to be so I don't know if this is a common pattern to use. Thoughts?

**Comment by natewiebe13** [comment]
Part of my goal with this one is to make it a no brainer to use on a project. A lot of time we have a starting point theme, but then we need to implement designs and branding for the client. The way I would like to have my team use this is to have our starter theme using this with the default icons and then if icons need to be slightly tweaked or a couple of new icons need to be added. We can just add them and use the same template functionality as before. This also could allow us to use aliases like described in #29

Part of my concern is what if we only keep using a couple or no stock icons. There's a chance that the lib might get removed, but I think it would be very simple to make it a bit more generic and get a lot more usability out of it.

I do understand that it then feels to shift more towards an icon manager than a strict php port of feather icons, but I know my team would get a lot more value if this feature existed.

Also regarding extending the class, that is possible, but especially once we have a symfony bundle or drupal module, extending becomes a lot more tedious and I would anticipate people would just make twig partials and include those instead of extending and trying to inject the class instead. We would also then likely want to add interfaces for the classes we have as well if we want people to extend them.

Let me know what you think.

**Comment by michaelsavchuk** [comment]
That makes sense. I don't see a big issue with doing it this way as long as the library user is expected to make sure that their icons are compatible with feather (with the default attributes and our customizations/helpers and all).

**Comment by natewiebe13** [comment]
I did some real world testing with this feature. Looking at existing icon sets, all other major icons fill the contents of the svg, rather than using an outline. This makes this feature not worth implementing unless we end up having a specific reason/request. Otherwise we're looking more into creating a generic icon lib, rather than making Feather Icons easily available and configurable in PHP. I'm going to close this one out for now.
