### ISSUE TITLE
Icon Objects

### ISSUE THREAD

**Issue by natewiebe13** [Pixelrobin/php-feather#19]
Instead of just returning strings, we should have a php object that represents an icon. This adds the ability to use services, middlewares, etc that can tweak icon attributes if needed making this system much more flexible.

**Comment by michaelsavchuk** [comment]
Interesting idea. I'm interested in how something like this would look though. There's not a ton of complex stuff going on, just attributes and content.

My initial thought is that this can potentially be done by extracting some the `Icons->get()` logic into two steps:
* A function to get a data object representing an icon
* A function to render the icon as an html string and return it

That means people can extend the `Icons` class to do some custom stuff like rendering if they want to.

Would be nice to use `Icons->get()` and `Icons->toSvg()`. Not a huge fan of changing what functions do but we're already changing the default behavior of `Icons->get()` in v2.0.

Thoughts?

**Comment by natewiebe13** [comment]
The way I see this working would make it feel the same way it currently does. The added benefit is that we have an object representation that can be manipulated. For more context, the projects I typically work on have controllers that render templates with data provided by services that are used for pages and APIs and don't have context about how the data will be used. If we want to generate an icon there, we might want to change some attribute just before it's rendered. If the icon was just a string, we would need to parse it, modify, then re-render it. Instead if it's already an object, we can call a function on it and render it for the first time.

I think the best way to explain this is to get a draft PR together so you can see what I'm thinking. It'll come your way soon!

**Comment by natewiebe13** [comment]
See #34
