### ISSUE TITLE
Automatically build on new Feather release

### ISSUE THREAD

**Issue by Pixelrobin** [Pixelrobin/php-feather#3]
Something needs to be set up to automatically update the repo when a new Feather release is made. Not sure the best way to do that at the moment, but I'll be looking at it.

**Comment by natewiebe13** [comment]
To paraphrase my response to #6, I think we should create a PHP script that will use assets packagist to pull in feather icons and will build a php file that has an array (or similar) of icons and have that committed. We can then create a Github Action to run that daily and open a PR as needed.

**Comment by natewiebe13** [comment]
This depends on #21
