### ISSUE TITLE
Contributor Attribution

### ISSUE THREAD

**Issue by michaelsavchuk** [Pixelrobin/php-feather#48]
At this point most of this code here is not my own, and I feel like at the very least the top contributors should get prominent recognition on the README.

I'm thinking a simple list might work for this small of a project, but also maybe something like https://github.com/all-contributors/all-contributors, if that's not too overkill.

Something to consider before v2 is released, or right after.

**Comment by natewiebe13** [comment]
If we did want to use a simpler list, I like the format of this one: https://github.com/sass/node-sass#maintainers

**Comment by natewiebe13** [comment]
I'm not sure when it was added, but this is now in the GitHub sidebar. I'm going to close this for now based on that.

![image](https://user-images.githubusercontent.com/759228/192296476-213c84b1-bf02-4fd3-9340-aba6167e3e9a.png)
