### ISSUE TITLE
Preload all icons

### ISSUE THREAD

**Issue by xavivars** [Pixelrobin/php-feather#5]
Opening a file everytime a new icon is requested is a huge performance hit if there are multiple icons in the same page. Ideally, there should be a build process to bundle all icons into a single file, on top of individual files, similar to how the defaultAttributes is created.

Maybe offering that at initialization time in the Icons class, to decide whether to preload all icons or not.

**Comment by michaelsavchuk** [comment]
This is resolved in #27 and will be included in v2.0 onwards.
