### ISSUE TITLE
Release of 2.0

### ISSUE THREAD

**Issue by projector22** [Pixelrobin/php-feather#50]
What still needs to be done to release v2.0? Can I help?

**Comment by natewiebe13** [comment]
At this point I think it's just a matter of updating the readme a bit and adding some attributions. One thing to note is the Feather icons project seems to be mostly abandoned at this point and Lucide icons seems to be the successor/fork. If you'd like to use Lucide with the same functionality as v2 of this lib, I've been publishing updates to https://github.com/natewiebe13/php-lucide

If you'd prefer to stick with Feather, I'll try to get v2 published sometime over the next week or so.

That being said, have you had a chance to try out the v2 alpha? It'd be great to get some feedback before solidifying the v2 release in case there's some changes we could make to improve the API.

**Comment by projector22** [comment]
Thanks mate, I'll check out Lucide - the icons are the same as Feather?

I'll also grab that alpha build and let you know if I have any issues. I appreciate the response

**Comment by natewiebe13** [comment]
They are the same in terms of how the SVGs are actually built. I'm guessing there's been some tweaks for consistency, but they're generally very similar from what I've compared.

**Comment by natewiebe13** [comment]
v2 has been fully released!
