### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by natewiebe13** [Pixelrobin/php-feather#9]
Come across this project wanting to use Feather Icons without having to use javascript. I would like to start using this in more projects, but I do feel like there are some updates that should be made; update php requirements to be more modern, more docs, formatting, a bit of refactoring. Before jumping into a bunch of PRs, I would like to know your thoughts on what should be done to ensure we're aligned on what should and shouldn't be done.

I'd be curious to know where you would like this project to go and if you'd be open to another maintainer to help out.

**Comment by Pixelrobin** [comment]
Hey @natewiebe13 I'm sorry this issue completely got lost in my notifications and for replying almost a year later. I don't personally have a need for this project anymore, but I am still open to contributions.

**Comment by Pixelrobin** [comment]
That being said, I am open to change ownership or add another maintainer. I'll be reviewing the PRs sent so far.

**Comment by natewiebe13** [comment]
I think we can close this one. I'll be working with Pixelrobin to make some improvements to the project.
